# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/pipe/pipe_SOC/pipe_SOC.cache/wt [current_project]
set_property parent.project_path D:/pipe/pipe_SOC/pipe_SOC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/pipe/pipe_SOC/pipe_SOC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/Administrator/Desktop/pipecpu/cut2.coe
read_verilog -library xil_defaultlib {
  D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/FPGATop/MIO_BUS.v
  D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/FPGATop/Multi_CH32.v
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/RF.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/alu.v}
  D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/FPGATop/clk_div.v
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/dffe32.v}
  D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/FPGATop/dm.v
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/mux.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipecpu.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipecu.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipedereg.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipeemreg.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipeexe.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipeid.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipeif.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipeir.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipemwreg.v}
  {D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/success - metoo2/pipepc.v}
  D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/FPGATop/seg7x16.v
  D:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/imports/pipecpu/FPGATop/pipe_Top.v
}
read_ip -quiet d:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all d:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/ip/imem/imem_ooc.xdc]
set_property is_locked true [get_files d:/pipe/pipe_SOC/pipe_SOC.srcs/sources_1/ip/imem/imem.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/pipe/pipe_SOC/pipe_SOC.srcs/constrs_1/imports/pipecpu/Nexys4DDR_CPU.xdc
set_property used_in_implementation false [get_files D:/pipe/pipe_SOC/pipe_SOC.srcs/constrs_1/imports/pipecpu/Nexys4DDR_CPU.xdc]


synth_design -top IP2SOC_Top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef IP2SOC_Top.dcp

catch { report_utilization -file IP2SOC_Top_utilization_synth.rpt -pb IP2SOC_Top_utilization_synth.pb }
